# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Category.destroy_all
Product.destroy_all
Favorite.destroy_all

#Users
u1 = User.create(name: "Mari", username: "mari", password: "123")

#Categories
c1 = Category.create(name: "Skincare")
c2 = Category.create(name: "Makeup")
c3 = Category.create(name: "Hair")

#Products: skincare
p1 = Product.create(brand_name: "Living Libations", product_name: "Best Skin Ever - Seabuckthorn", description: "Silky Seabuckthorn Best Skin Ever, resets skin to its natural state of luminous, sparkling wonder! Seabuckthorn Best Skin Ever is an all-in-one cleanser, exfoliator, and moisturizer that can be used to grace the face, tempt the nose, and make skin sing from head to toes!", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/seabuckthorn-best-skin-ever-50ml_hires_197d9657-7bc3-41fd-8e80-3f3637bc0256_1024x1024@2x.jpg?v=1594054132", website: "https://livinglibations.com/collections/best-sellers/products/best-skin-ever-seabuckthorn", category_id: c1.id)

p2 = Product.create(brand_name: "Living Libations", product_name: "Rose Renewal + Frankincense Firming Fluid", description: "Living Libations Rose Renewal + Frankincense Firming Fluid is a picture-perfect moisturizer for summer skin, humid climates and wisdom skin. This lightweight emollient is endowed with extra essences that firm sagging skin, ease fine lines and wrinkles. This gorgeously glowing, light and lovely liquid replenishes skin tone. It is a fabulous fluid of fortification that will keep your skin sublime as it nourishes and moisturizes the face while it minimizes the appearance of scar tissue, fine lines and protects skin exposed to the environmental elements.", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/rose-renewal-100ml_hires_1_c9a6aa99-d0b5-4037-bbdd-3ac2b62566fc_1024x1024@2x.jpg?v=1593605920", website: "https://livinglibations.com/collections/skin-care/products/rose-renewal-frankincense-firming-fluid", category_id: c1.id)

p3 = Product.create(brand_name: "Living Libations", product_name: "Rose Glow Crème", description: "Living Libations Rose Glow Crème is a daydream of rose’s revitalizing rays that embraces pores with rosy adore. This crème of botanical grace will bring balance to your benevolent face as it sinks gracefully into your complexion. It harmonizes dry, pallid and wise skin with a pure palette of botanical bounty. The elegant pink hue and rosy aroma will grace your senses with a symphony of beauty for soft resilient skin.", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/rose-glow-50ml-lid-off_hires_1_10a805a4-209f-49b9-86ed-2d9ca3692321_1024x1024@2x.jpg?v=1594927193", website: "https://livinglibations.com/collections/skin-care/products/rose-glow-creme", category_id: c1.id)

p4 = Product.create(brand_name: "Living Libations", product_name: "DewDab", description: "For in the dew of little things, the skin is refreshed and replenished. DewDab is our soothing spot on serum that is designed to diminish the appearance of fine lines, scars, bumps, couperose and melasma on your skin. Dab directly on areas needing TLC or blend with a Best Skin Ever or Libations Facial Serum. For the most even skin tone and smoothest complexion, DewDab is the go-to Dab. It tones skin of issues that somehow appear overnight. Dab, dress and caress your skin after cleansing with the Best Skin Ever every morning and evening for glowing results!", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/dew-dab-5ml_hires_1_620c98c9-2c6a-4099-9673-ffa00bacaa42_1024x1024@2x.jpg?v=1593515198", website: "https://livinglibations.com/collections/skin-care/products/dewdab", category_id: c1.id)

p5 = Product.create(brand_name: "Living Libations", product_name: "Ensorcell Serum", description: "Stubborn skin issues take heed! Living Libations Ensorcell Serum is the spot-on solution for the stubborn skin imbalances, including sagging skin, loss of elasticity, puffiness and redness, age spots and uneven skin tone. This super-stimulating liquid serum brings dry, dull and listless pallor back to life. Ensorcell Serum seeps seamlessly into the skin delivering restorative, concentrated supercritical extracts, fresh pressed lipids, and MSM-infused essential oils.", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/ensorcell-serum-30ml_hires_1_06da7ba5-3031-4ea1-bca3-6ed4d290280d_1024x1024@2x.jpg?v=1593606165", website: "https://livinglibations.com/collections/skin-care/products/ensorcell-serum", category_id: c1.id)

p6 = Product.create(brand_name: "Living Libations", product_name: "Rose Glow Serum", description: "This silky smooth face serum creates a radiant, dewy glow that restores, adores and harmonizes every face adorned by its grace. The floral glory of Rose Otto in Living Libations Rose Glow Serum possesses an exceptional affinity for wise skin and skin requiring gentle care. Soften the skin into rose-woven silk with this pure rose-filled elixir that blesses with a dewy, fresh face and a sweetened disposition. Righteous for wrinkles! Royal for pallid complexions! Excellent for evening out skin tone! A few drops in the morning and a few drops at night alight the skin with pure, fresh, feather-light moisture.", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/rose-glow-serum-30ml_hires_1_6083a0dd-8a43-4704-83a5-f721d5af1cf9_1024x1024@2x.jpg?v=1593516714", website: "https://livinglibations.com/collections/skin-care/products/roseglow-serum", category_id: c1.id)

p7 = Product.create(brand_name: "Living Libations", product_name: "All Seeing Opulent Eye Crème", description: "Opulent All Seeing Opulent Eye Crème is a thick, rich, luxurious crème that effortlessly sinks into skin and is specially formulated to nourish the tender skin around the eyes. All Seeing Opulent Eye Crème is made by whipping herb-infused Jojoba, Tamanu, Shea, Borage, and Avocado oils with refreshing Rosewater and Aloe Vera. We then infuse this mixture with an entire palette of nourishing essences to soothe and infuse the delicate skin around the eyes. Dry skin, fine lines, and wrinkles will enjoy an influx of moisture with this caring crème, which is perfect to wear under make-up (and may also be graced upon the entire face). For a super-silky nighttime treat combine a diminutive dollop of All Seeing Opulent Eye Crème with a drop of Open Sky Eye Serum to reduce the appearance of dark circles, puffiness and fine lines and wake up feeling renewed.", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/all-seeing-eye-cream-15ml_hires_8d0d3993-a9ec-47c5-8705-c0f6278b14c2_1024x1024@2x.jpg?v=1594927301", website: "https://livinglibations.com/collections/skin-care/products/all-seeing-eye-creme", category_id: c1.id)

p8 = Product.create(brand_name: "Living Libations", product_name: "Best Skin Ever - Sandalwood", description: "There is no such thing as “too sensitive” – especially when it comes to your skin! For people with delicate skin, we have created a delicious, deeply nutritious, moisture-rich manna to care for every inch of your skin! Created with the botanical intelligence of organic essential oils, our Sandalwood Best Skin Ever will reveal your skin at its finest. Sandalwood Best Skin Ever is an exquisite addition to our Best Skin Ever blends that are perfect for washing and moisturizing your skin from head to toe. This new creation is a combination of flawless botanicals blended in pitch perfect ratio. The result is a nourishing elixir of liquid-love, a soothing serum to delight the grace of your body and face. So what is so special about Sandalwood Best Skin Ever? It contains organic and essential oils that are not only powerfully effective; they are gentle enough for the most sensitive skin (and the most sensitive souls!).", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/sandalwood-best-skin-ever-50ml_hires_1_9cc6aaee-cb96-4029-b04a-1faaa1ab0229_1024x1024@2x.jpg?v=1593521091", website: "https://livinglibations.com/collections/skin-care/products/best-skin-ever-sandalwood", category_id: c1.id)

p9 = Product.create(brand_name: "Living Libations", product_name: "Frankincense Face Tonic", description: "Refreshing Frankincense Face Tonic is a skin-quenching drink that drenches pores with its cherished moisture that skin adores. Fundamentally, this Frankincense water is an aqueous version of the aromatic essential oil. It is a face tonic with a fine fragrance and ethereal effectiveness for hydrating skin. Frankincense Face Tonic gives instant irrigation of epic proportions. It refreshes as it infuses the face with the ancient power of a double dose Frankincense, which is a smoothing, soothing “pick-me-up in a bottle.” Turn caring for your skin into a mediation with this fortifying molecular mist that may be used to revitalize skin after cleansing, shaving and to revive the spirit anytime of day.", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/frankincense-face-tonic-30ml_hires_18e4ad45-70d9-4ca9-a928-32fb3141b2ad_1024x1024@2x.jpg?v=1593619634", website: "https://livinglibations.com/collections/skin-care/products/frankincense-face-tonic", category_id: c1.id)

p10 = Product.create(brand_name: "Living Libations", product_name: "Green Papaya + Lime Mask", description: "Living Libations Green Papaya + Lime Mask gently tones and exfoliates skin while maximizing moisture and expanding elasticity. This mask is made with fruit-derived enzymes along with raw sugar cane as supple exfoliating agents. If your face, neck or décolleté could benefit from enzymatic exfoliating, firming and moisturizing our carefully crafted mask does the task. Glistening Aloe Vera gel and Golden Jojoba encourage marvelous moisture, elasticity, and suppleness. Encouraging enzymes from Lemons and Limes blended with raw sugar, Green Papaya and Pineapple enzymes clears the pores and improves the overall texture and suppleness of the skin. Rosewater, Comfrey and Horsetail strengthen skin and renovate its resilience. Green Papaya + Lime Mask will prepare you to face the world as you unmask and reveal radiant, supple skin.", image_url: "https://cdn.shopify.com/s/files/1/0301/8729/0762/products/green-papaya-lime-mask-30ml_preview_d007133a-c921-468e-9b6e-b307af3c97c3_1024x1024@2x.jpg?v=1593433440", website: "https://livinglibations.com/collections/skin-care/products/green-papaya-lime-mask", category_id: c1.id)

p11 = Product.create(brand_name: "100% Pure", product_name: "Coffee Bean Caffeine Eye Cream", description: "Anti-inflammatory, caffeine rich green tea and coffee de-puff while increasing circulation to brighten dark circles. Concentrated with potent anti-aging vitamins and antioxidants to awaken the eye area, and nourishing rosehip oil for softer, more youthful skin.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_507,c_limit,dpr_1.0/v1580771914/products/1FMCBEC0.3OZ/1FMCBEC0.3OZ_Coffee_Bean_Eye_Cream_0.3oz_Primary", website: "https://www.100percentpure.com/collections/eye-care/products/coffee-bean-caffeine-eye-cream-0-3-oz", category_id: c1.id)

p12 = Product.create(brand_name: "100% Pure", product_name: "Vitamin C Serum", description: "Lightweight, stabilized vitamin C serum made in a base of hydrating and soothing aloe gel. This serum also helps to firm and brighten skin tone, while promoting collagen production. Includes radiance-boosting green apple and grape, plus alpha lipoic acid (ALA) for fighting oxidative damage that can prematurely age or darken the skin.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_392,c_limit,dpr_1.0/v1580774841/products/1FMVCS/1FMVCS_Vitamin_C_Serum_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/vitamin-c-serum", category_id: c1.id)

p13 = Product.create(brand_name: "100% Pure", product_name: "Fermented Rice Water Toner", description: "Fermented rice water (Sake) is rich in enzymes, amino acids, malic acid, minerals, and vitamins to deeply soften, nourish, and give your skin a healthier glow. A concentration of white mulberry, shiitake mushroom, licorice and citrus balances skin tone, lessens the appearance of dark spots, and brightens. Our Fermented Rice Toner also includes hyaluronic acid, sodium PCA, and vegetable glycerin to promote skin hydration and plumping.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_392,c_limit,dpr_1.0/v1580776257/products/1FFRWT/1FFRWT_Fermented_Rice_Water_Toner_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/fermented-rice-water-toner", category_id: c1.id)

p14 = Product.create(brand_name: "100% Pure", product_name: "Anti Acne Sheet Mask", description: "Our skin clarifying sheet mask is made with salicylic acid to help unclog pores; naturally antibacterial tea tree, parsley, and rosemary to purify; and seaweed and basil to detoxify. Unlike other blemish treatments, this mask is non-stripping and nourishing for skin, made with plant ceramides and hyaluronic acid to feed skin with soothing hydration. This natural sheet mask is made from sustainable and antibacterial bamboo cloth and free of artificial fragrances, chemical preservatives, harsh detergents and unhealthy, toxic ingredients.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_400,c_limit,dpr_1.0/v1580763120/products/1FSMDDAA/1FSMDDAA_Anti-Acne_Sheet_Mask_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/sheet-mask-anti-acne-masks", category_id: c1.id)

p15 = Product.create(brand_name: "100% Pure", product_name: "Deep Hydration Sheet Mask", description: "Intensely hydrating mask replenishes dry, thirsty skin with aloe juice and a nourishing trio of cucumber, hyaluronic acid, and plant ceramides. This water-drenching blend of botanicals locks in long-lasting hydration to leave skin ultra plump, soft, and supple. Anti-inflammatory rosehip, ylang ylang, and chamomile help to calm the skin, while beta glucan soothes and moisturizes. This natural sheet mask is made from sustainable and antibacterial bamboo cloth and free of artificial fragrances, chemical preservatives, harsh detergents and unhealthy, toxic ingredients.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_400,c_limit,dpr_1.0/v1580764639/products/1FSMDDH/1FSMDDH_Sheet_Mask_Deep_Hydration_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/sheet-mask-deep-hydration-masks", category_id: c1.id)

p16 = Product.create(brand_name: "100% Pure", product_name: "Charcoal Clay Cleanser", description: "Deeply purifying facial cleanser in a base of detoxifying, pore minimizing bamboo charcoal and skin purging clay. Washes away makeup and other impurities while refreshing skin and banishing excess oil, without stripping or dehydrating. Anti-bacterial essential oils of spearmint, lemongrass and skin brightening lemon water invigorate and give you a healthy, glowing complexion.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_400,c_limit,dpr_1.0/v1582836947/products/1FCCC/1FCCC_Charcoal_Clay_Cleanser_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/charcoal-clay-cleanser", category_id: c1.id)

p17 = Product.create(brand_name: "100% Pure", product_name: "Acai Pulp Facial Scrub", description: "Intensive, concentrated facial scrub designed to give pores a deep sweep for a glowing, more youthful complexion. Because of the concentration strength of this nutrient dense formula, always use on wet skin (the more water you incorporate, the gentler the exfoliation). Crushed organic acai berries deeply nourish and brighten with essential vitamins, minerals, antioxidants, fatty acids, and vitamins A and C.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_392,c_limit,dpr_1.0/v1580773082/products/1FAPFS/1FAPFS_Acai_Pulp_Facial_Scrub_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/acai-pulp-facial-scrub", category_id: c1.id)

p18 = Product.create(brand_name: "100% Pure", product_name: "Matcha Oat Milk Nourishing Mask", description: "Deeply nourishing, softening mask concentrated with restorative and skin-beneficial nutrients. Beta glucan-rich colloidal oats soothe and moisturize; coconut milk softens and fortifies; calendula calms; hyaluronic acid plumps skin with hydration; rice ceramides increase suppleness, and organic matcha green tea restores and protects against environmental damage.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_392,c_limit,dpr_1.0/v1567701660/products/FMOMNM/1FMOMM_Matcha_Oat_Milk_Nourishing_Mask_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/matcha-oat-milk-nourishing-mask", category_id: c1.id)

p19 = Product.create(brand_name: "100% Pure", product_name: "Lavender Tonique", description: "Soothing tonique purifies and cleanses pores while refreshing and hydrating your complexion. DMAE firms, lifts, and lessens lines and wrinkles. MSM is an organic sulfur found in vegetables like broccoli, brussel sprouts, etc. which is known to help skin firmness.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_392,c_limit,dpr_1.0/v1580776916/products/1FTOLT/1FTOLT_Lavender_Tonique_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/lavender-tonique?variant=36540617678", category_id: c1.id)

p20 = Product.create(brand_name: "100% Pure", product_name: "Super Fruit Oil Nourishing Eye Cream", description: "Superfruit oils contain the highest concentration of nutrients, making them extremely nourishing and moisturizing. Powerful, potent superfruit antioxidants and vitamins in this daily eye cream formula promote elasticity, while lessening the appearance of fine lines and wrinkles.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_392,c_limit,dpr_1.0/v1580758532/products/1FSFONEC/1FSFONEC_Super_Fruit_Oil_Nourishing_Eye_Cream_Primary", website: "https://www.100percentpure.com/collections/skin-care/products/super-fruit-oil-nourishing-eye-cream", category_id: c1.id)

p21 = Product.create(brand_name: "Blue Beautifly", product_name: "Papaya Enzyme Mask", description: "Papaya Enzyme Mask uses a highly effective combination of papaya and pineapple enzymes to gently slough away dead skin cells and impurities. Your complexion will look brighter and feel revitalized, soft, and supple.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2019/04/papaya.jpg", website: "https://www.bluebeautifly.com/shop/papaya-enzyme-mask/", category_id: c1.id)

p22 = Product.create(brand_name: "Blue Beautifly", product_name: "Coconut Exfoliant", description: "Deliciously invigorating! Coconut Exfoliant combines phytonutrient-rich coconut extract with finely ground coconut shell powder to slough away dead skin cells, revealing a fresh and revitalized complexion.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2019/07/coconut-1.jpg", website: "https://www.bluebeautifly.com/shop/coconut-exfoliant/", category_id: c1.id)

p23 = Product.create(brand_name: "Blue Beautifly", product_name: "Pineapple Enzyme Exfoliant", description: "A tropical treat with twice the exfoliating power! Pineapple Enzyme Exfoliant uses the natural fruit enzymes of pineapple and papaya to slough off dead skin cells while gentle rice bran beads polish away impurities. Your complexion will look brighter and more luminous.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2019/07/pineapple.jpg", website: "https://www.bluebeautifly.com/shop/pineapple-enzyme-exfoliant/", category_id: c1.id)

p24 = Product.create(brand_name: "Blue Beautifly", product_name: "Bilberry Antioxidant Mask", description: "Bilberry Antioxidant Mask is bursting with powerful botanical antioxidants and vitamins to hydrate and tone the skin for a brighter, more radiant, and youthful complexion.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2019/07/bilberry.jpg", website: "https://www.bluebeautifly.com/shop/bilberry-antioxidant-mask/", category_id: c1.id)

p25 = Product.create(brand_name: "Blue Beautifly", product_name: "Rosehip Moisturizer", description: "Rich in antioxidants, Rosehip Moisturizer promotes a supple and harmonized skin botanically. It reduces the appearance of fine lines and wrinkles and leaves the skin feeling firm, smooth, and more hydrated.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2014/08/rosehip_w.jpg", website: "https://www.bluebeautifly.com/shop/rosehip-moisturizer/", category_id: c1.id)

p26 = Product.create(brand_name: "Blue Beautifly", product_name: "Organic Calendula Cleansing Oil", description: "Organic Calendula Cleansing Oil dissolves makeup and impurities, without stripping away the skin’s natural protective barrier. Calming calendula soothes and nourishes while essential fatty acids leave the skin feeling soft and supple with a healthy radiant glow. Use daily or as a pre-cleansing oil to remove makeup.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2019/07/CalenduaCleansingOil_w2.jpg", website: "https://www.bluebeautifly.com/shop/organic-calendula-cleansing-oil/", category_id: c1.id)

p26 = Product.create(brand_name: "Blue Beautifly", product_name: "Rosemary Cleanser", description: "Rosemary Cleanser makes the skin feel soft and sparkling by hydrating and removing dirt and makeup gently, yet effectively.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2019/10/BBFLY_rosemary.jpg", website: "https://www.bluebeautifly.com/shop/rosemary-cleanser/", category_id: c1.id)

p27 = Product.create(brand_name: "Blue Beautifly", product_name: "Organic Arnica Body Oil Serum", description: "Organic Arnica Body Oil Serum conditions and soothes the skin and body with nourishing Ayurvedic herbal extracts and omega-rich oils.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2020/01/arnica_w-1.jpg", website: "https://www.bluebeautifly.com/shop/organic-arnica-body-oil-serum/", category_id: c1.id)

p28 = Product.create(brand_name: "Blue Beautifly", product_name: "lluminating Mud Mask Powder", description: "Illuminating Mud Mask Powder delivers bright and luminous complexion by combating sun damage, reducing the appearance of age spots, and reviving dull skin naturally.  The synergetic botanical blend of bearberry, licorice, olive leaf, and lavender combined with the mineral-rich Moroccan rhassoul and French rose clays brighten and reveal the skin’s youthful glow.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2015/11/BlueB-IlluminatingMudMaskPowder.jpg", website: "https://www.bluebeautifly.com/shop/illuminating-mud-mask-powder/", category_id: c1.id)

p29 = Product.create(brand_name: "Blue Beautifly", product_name: "Balancing Mud Mask Powder", description: "Balancing Mud Mask Powder brings out the skin’s natural clarity by removing impurities and excess oil naturally.  The Ayurvedic blend of triphala, ashwagandha, and turmeric are combined with the mineral-rich fuller’s earth (multani mitti) and green clays to invigorate the skin and remove debris and other impurities from the pores.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2015/11/BlueB-BalancingMudMaskPowder.jpg", website: "https://www.bluebeautifly.com/shop/balancing-mud-mask-powder/", category_id: c1.id)

p30 = Product.create(brand_name: "Blue Beautifly", product_name: "Organic Rose Toner", description: "Organic Rose Toner freshens and energizes the skin with the revitalizing and restoring qualities of rose.", image_url: "https://www.bluebeautifly.com/wp-content/uploads/2019/02/rose_w-e1552678218175.jpg", website: "https://www.bluebeautifly.com/shop/organic-rose-toner/", category_id: c1.id)


#Products: makeup
p31 = Product.create(brand_name: "100% Pure", product_name: "Fruit Pigmented® Cocoa Butter Matte Lipstick", description: "An innovative matte lipstick formula that keeps lips moisturized all day long while providing stunning, long-lasting color. Formulated with chocolate and antioxidant-rich fruit pigments like cherry, blueberry, and peach. Made with a nourishing blend of cocoa butter, shea butter, and vitamin E to moisturize and protect delicate lips from dryness.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_600,c_limit,dpr_1.0/l_Badges:badges,w_0.3,y_-0.3,x_0.34,fl_relative,pg_name:2019-think-dirty/v1574894833/products/1CCBMLPP/1CCBMLPP_Matte_Lipstick_Prickly_Pear_Primary", website: "https://www.100percentpure.com/collections/lipstick/products/fruit-pigmented-cocoa-butter-matte-lipstick", category_id: c2.id)

p32 = Product.create(brand_name: "100% Pure", product_name: "Fruit Pigmented® Pretty Naked Palette", description: "Fruit pigmented® makeup palette celebrates neutral tones and soft shimmer to enhance and beautify your complexion. Includes eyeshadows, blush, and highlighter.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_507,c_limit,dpr_1.0/v1582246714/products/1CNP/1CNP_Pretty_Naked_Palette_Primary", website: "https://www.100percentpure.com/collections/eyeshadow/products/fruit-pigmented-pretty-naked-palette", category_id: c2.id)

#Products: hair
p33 = Product.create(brand_name: "100% Pure", product_name: "Burdock & Neem Healthy Scalp Shampoo", description: "Purifying formula unclogs pores, stimulates circulation, and alleviates dryness, itching, and flaking. With added hydration for healthier scalp and hair.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_507,c_limit,dpr_1.0/v1580172517/products/1HCSBNHS13OZ/1HCSBNHS13OZ_Burdock_Neem_Healthy_Scalp_Shampoo", website: "https://www.100percentpure.com/collections/shampoo/products/burdock-neem-healthy-scalp-shampoo-13oz", category_id: c3.id)

p34 = Product.create(brand_name: "100% Pure", product_name: "Argan Oil", description: "PLightweight and restorative Argan Oil is rich in vitamin E, phenols, carotenes, squalene, and essential fatty acids to deeply moisturize, nourish, and soften.", image_url: "https://cdn.no-toxic.com/q_auto:best,f_auto,fl_lossy,w_507,c_limit,dpr_1.0/v1563386326/products/1FMOAO1.6OZ/1FMOAO1.6OZ_Argan_Oil_Primary", website: "https://www.100percentpure.com/products/organic-argan-oil", category_id: c3.id)

#Favorites
f1 = Favorite.create(user_id: u1.id, product_id: p1.id)
f2 = Favorite.create(user_id: u1.id, product_id: p2.id)
f3 = Favorite.create(user_id: u1.id, product_id: p3.id)
